// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseTask.Data.Migrations
{
    [DbContext(typeof(DatabaseTaskDbContext))]
    [Migration("20250528110455_FixedForeignKeys")]
    partial class FixedForeignKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseTask.Core.Models.AnonymousFeedback", b =>
                {
                    b.Property<int>("Feedback_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Feedback_ID"));

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Feedback_ID");

                    b.ToTable("AnonymousFeedbacks");
                });

            modelBuilder.Entity("DatabaseTask.Core.Models.Child", b =>
                {
                    b.Property<int>("Child_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Child_ID"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Employee_ID")
                        .HasColumnType("int");

                    b.Property<int>("Employee_ID1")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Child_ID");

                    b.HasIndex("Employee_ID1");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("DatabaseTask.Core.Models.Department", b =>
                {
                    b.Property<int>("Department_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Department_ID"));

                    b.Property<string>("Department_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Department_ID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("DatabaseTask.Core.Models.Employee", b =>
                {
                    b.Property<int>("Employee_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Employee_ID"));

                    b.Property<int?>("Department_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Department_ID1")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("JobTitleJob_Title_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Job_Title_ID")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("SocialSecurityNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Employee_ID");

                    b.HasIndex("Department_ID1");

                    b.HasIndex("JobTitleJob_Title_ID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DatabaseTask.Core.Models.EmployeeAccess", b =>
                {
                    b.Property<int>("Employee_Access_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Employee_Access_ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Employee_ID")
                        .HasColumnType("int");

                    b.Property<int>("Employee_ID1")
                        .HasColumnType("int");

                    b.HasKey("Employee_Access_ID");

                    b.HasIndex("Employee_ID1");

                    b.ToTable("EmployeeAccesses");
                });

            modelBuilder.Entity("DatabaseTask.Core.Models.Equipment", b =>
                {
                    b.Property<int>("Equipment_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Equipment_ID"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Equipment_ID");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("DatabaseTask.Core.Models.HealthCheck", b =>
                {
                    b.Property<int>("Health_Check_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Health_Check_ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Employee_ID")
                        .HasColumnType("int");

                    b.Property<int>("Employee_ID1")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Health_Check_ID");

                    b.HasIndex("Employee_ID1");

                    b.ToTable("HealthChecks");
                });

            modelBuilder.Entity("DatabaseTask.Core.Models.JobTitle", b =>
                {
                    b.Property<int>("Job_Title_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Job_Title_ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Job_title_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Job_Title_ID");

                    b.ToTable("JobTitles");
                });

            modelBuilder.Entity("DatabaseTask.Core.Models.Loan", b =>
                {
                    b.Property<int>("Loan_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Loan_ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Employee_ID")
                        .HasColumnType("int");

                    b.Property<int>("Employee_ID1")
                        .HasColumnType("int");

                    b.Property<int>("Equipment_ID")
                        .HasColumnType("int");

                    b.Property<int>("Equipment_ID1")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoanLastDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LoanStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Loan_ID");

                    b.HasIndex("Employee_ID1");

                    b.HasIndex("Equipment_ID1");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("DatabaseTask.Core.Models.SickLeave", b =>
                {
                    b.Property<int>("Sick_leave_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sick_leave_ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Employee_ID")
                        .HasColumnType("int");

                    b.Property<int>("Employee_ID1")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Sick_leave_ID");

                    b.HasIndex("Employee_ID1");

                    b.ToTable("SickLeaves");
                });

            modelBuilder.Entity("DatabaseTask.Core.Models.Vacation", b =>
                {
                    b.Property<int>("Vacation_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Vacation_ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Employee_ID")
                        .HasColumnType("int");

                    b.Property<int>("Employee_ID1")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Extra_Child_Day_Vacation")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Vacation_ID");

                    b.HasIndex("Employee_ID1");

                    b.ToTable("Vacations");
                });

            modelBuilder.Entity("DatabaseTask.Core.Models.Child", b =>
                {
                    b.HasOne("DatabaseTask.Core.Models.Employee", "Employee")
                        .WithMany("Children")
                        .HasForeignKey("Employee_ID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DatabaseTask.Core.Models.Employee", b =>
                {
                    b.HasOne("DatabaseTask.Core.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("Department_ID1");

                    b.HasOne("DatabaseTask.Core.Models.JobTitle", "JobTitle")
                        .WithMany("Employees")
                        .HasForeignKey("JobTitleJob_Title_ID");

                    b.Navigation("Department");

                    b.Navigation("JobTitle");
                });

            modelBuilder.Entity("DatabaseTask.Core.Models.EmployeeAccess", b =>
                {
                    b.HasOne("DatabaseTask.Core.Models.Employee", "Employee")
                        .WithMany("EmployeeAccesses")
                        .HasForeignKey("Employee_ID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DatabaseTask.Core.Models.HealthCheck", b =>
                {
                    b.HasOne("DatabaseTask.Core.Models.Employee", "Employee")
                        .WithMany("HealthChecks")
                        .HasForeignKey("Employee_ID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DatabaseTask.Core.Models.Loan", b =>
                {
                    b.HasOne("DatabaseTask.Core.Models.Employee", "Employee")
                        .WithMany("Loans")
                        .HasForeignKey("Employee_ID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Models.Equipment", "Equipment")
                        .WithMany("Loans")
                        .HasForeignKey("Equipment_ID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("DatabaseTask.Core.Models.SickLeave", b =>
                {
                    b.HasOne("DatabaseTask.Core.Models.Employee", "Employee")
                        .WithMany("SickLeaves")
                        .HasForeignKey("Employee_ID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DatabaseTask.Core.Models.Vacation", b =>
                {
                    b.HasOne("DatabaseTask.Core.Models.Employee", "Employee")
                        .WithMany("Vacations")
                        .HasForeignKey("Employee_ID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DatabaseTask.Core.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("DatabaseTask.Core.Models.Employee", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("EmployeeAccesses");

                    b.Navigation("HealthChecks");

                    b.Navigation("Loans");

                    b.Navigation("SickLeaves");

                    b.Navigation("Vacations");
                });

            modelBuilder.Entity("DatabaseTask.Core.Models.Equipment", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("DatabaseTask.Core.Models.JobTitle", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
